In [1]:
#Have to import libraries
import pandas as pd
import numpy as np

In [2]:
#Upload the data_file
df = pd.read_csv(r'E:\\Data Analysis\Data analysis 01.03.2022\Machine-Learning\Studymart\Class 6\insurance.csv')

In [3]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [5]:
# Checking null_value
df.isnull().any()

age         False
sex         False
bmi         False
children    False
smoker      False
region      False
charges     False
dtype: bool

# Label encoder

In [6]:
#step-01:We have to import LabelEncoder from sklearn.preprocessing library
from sklearn.preprocessing import LabelEncoder

In [7]:
#Step-2: We have to create an object of labelencoder
obj = LabelEncoder()

In [8]:
#Now, we hveto fit and transform those string columns with labelEncoder
df.sex = obj.fit_transform(df['sex'])
df.smoker = obj.fit_transform(df['smoker'])
df.region = obj.fit_transform(df['region'])

In [9]:
df.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

# Now Labelencoding with loop

In [10]:
#Step-1: Import  all required libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore') 
#for removing warnings because of another floating data of columns and encoded integer numeric value

In [11]:
#step-2: Upload data_file 
data_file= pd.read_csv(r'E:\\Data Analysis\Data analysis 01.03.2022\Machine-Learning\Studymart\Class 6\insurance.csv')

In [12]:
#Now try to select the string columns of the dataFrame by for loop and implement the conditions
for col in data_file.columns:
    if data_file[col].dtype==np.number:
        continue
    else:
        data_file[col]= obj.fit_transform(data_file[col])
""" the col will try to match every column of data_file and if those columns contain numerinc value (np.number) then col will
move to another columns(continue). when col will get a column which does not contain numeric value then then tahat column will
be sent through labelencoder object and fit and transform that columns
"""

' the col will try to match every column of data_file and if those columns contain numerinc value (np.number) then col will\nmove to another columns(continue). when col will get a column which does not contain numeric value then then tahat column will\nbe sent through labelencoder object and fit and transform that columns\n'

In [13]:
data_file.head()

age  sex     bmi  children  smoker  region      charges
0    1    0  27.900         0       1       3  16884.92400
1    0    1  33.770         1       0       2   1725.55230
2   10    1  33.000         3       0       2   4449.46200
3   15    1  22.705         0       0       1  21984.47061
4   14    1  28.880         0       0       1   3866.85520

# One Hot Encoding

In [14]:
# Step-1: Import all requird libraries
import pandas as pd
import numpy as np


In [15]:
# Step-2: upload data from desktop
data = pd.read_csv(r'E:\\Data Analysis\Data analysis 01.03.2022\Machine-Learning\Studymart\Class 6\insurance.csv')
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [38]:
#step-3:Now we have to check data type 
#data.info()

In [17]:
# here object type data are string data. Thus, we have to convert those object Dtype columns into numeric datatype columns


In [18]:
#Step-4:For one hot encoding, we have to create dummy columns for object dtype columns
sex_dummy = pd.get_dummies(data['sex'],drop_first=True,prefix='sex')
smoker_dummy = pd.get_dummies(data['smoker'],drop_first=True,prefix='smoker')
region_dummy = pd.get_dummies(data['region'],drop_first=True,prefix='region')


In [31]:
#sex_dummy


In [32]:
#smoker_dummy

In [37]:
#region_dummy

In [22]:
# Now we have to remove object data type columns from out data. Is there any way to remove those columns at a time?
New_data = data.drop('sex',axis=1)
New_data1 = New_data.drop('smoker',axis=1)
New_data2 = New_data1.drop('region',axis=1)

In [23]:
New_data2.head()

age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

In [24]:
#step-5: Now we have to concat New_data2 and dummy_data
One_Hot_ENcoded_data = pd.concat([New_data2,sex_dummy,smoker_dummy,region_dummy], axis=1)

In [25]:
One_Hot_ENcoded_data.head()

age     bmi  children      charges  sex_male  smoker_yes  region_northwest  \
0   19  27.900         0  16884.92400         0           1                 0   
1   18  33.770         1   1725.55230         1           0                 0   
2   28  33.000         3   4449.46200         1           0                 0   
3   33  22.705         0  21984.47061         1           0                 1   
4   32  28.880         0   3866.85520         1           0                 1   

   region_southeast  region_southwest  
0                 0                 1  
1                 1                 0  
2                 1                 0  
3                 0                 0  
4                 0                 0

In [26]:
data.nunique()

age           47
sex            2
bmi          548
children       6
smoker         2
region         4
charges     1337
dtype: int64

# Ordinal encoder

In [74]:
import pandas as pd
import numpy as np

In [75]:
Oridinal_data = pd.read_csv(r'E:\\Data Analysis\Data analysis 01.03.2022\Machine-Learning\Studymart\Class 6\insurance.csv')

In [76]:
Oridinal_data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [78]:
#checking how many dtat points are in a columns
Oridinal_data.sex.unique()

array(['female', 'male'], dtype=object)

In [79]:
gender = ['female', 'male']

In [80]:
Oridinal_data.smoker.unique()

array(['yes', 'no'], dtype=object)

In [86]:
smoking_condition = ['yes', 'no']

In [87]:
Oridinal_data.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [88]:
region_directions = ['southwest', 'southeast', 'northwest', 'northeast']

In [89]:
from sklearn.preprocessing import OrdinalEncoder

In [91]:
# OrdinalEncoder object
OrdinalEncoder_object = OrdinalEncoder(categories = [gender,smoking_condition,region_directions])

In [92]:
fitting_transformations_string_columns_region = OrdinalEncoder_object.fit_transform(Oridinal_data[['sex','smoker','region']])

In [93]:
print(fitting_transformations_string_columns_region)

[[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [0. 1. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]


In [94]:
New_Ordinal_encoded= pd.DataFrame(fitting_transformations_string_columns_region, columns=['sex','smoker','region'])

In [95]:
New_Ordinal_encoded.head()

sex  smoker  region
0  0.0     0.0     0.0
1  1.0     1.0     1.0
2  1.0     1.0     1.0
3  1.0     1.0     2.0
4  1.0     1.0     2.0

In [96]:
Oridinal_data['sex'] =New_Ordinal_encoded['sex']

In [97]:
Oridinal_data['smoker'] =New_Ordinal_encoded['smoker']

In [98]:
Oridinal_data['region'] =New_Ordinal_encoded['region']

In [99]:
Oridinal_data.head()

age  sex     bmi  children  smoker  region      charges
0   19  0.0  27.900         0     0.0     0.0  16884.92400
1   18  1.0  33.770         1     1.0     1.0   1725.55230
2   28  1.0  33.000         3     1.0     1.0   4449.46200
3   33  1.0  22.705         0     1.0     2.0  21984.47061
4   32  1.0  28.880         0     1.0     2.0   3866.85520